services:
  api01: &api01
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: 'localhost'
      DB_PORT: '5432'
      DB_USER: 'docker'
      DB_PASSWORD: 'docker'
      DB_DATABASE: 'rinha_api'
    depends_on:
      - postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '150MB'
  api02:
    <<: *api01

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50MB'
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=rinha_api
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'

volumes:
  postgres:
