services:
  api01: &api01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      NODE_ENV: 'production'
      PORT: 3333
      DB_USER: 'docker'
      DB_PASSWORD: 'docker'
      DB_NAME: 'rinha_api'
    depends_on:
      - postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '150MB'
  api02:
    <<: *api01
    ports:
      - '3334:3333'
    environment:
      PORT: 3334
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '50MB'
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=rinha_api
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '200MB'

volumes:
  postgres:
